# Generated by Django 3.2.5 on 2022-02-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20220201_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
