# Generated by Django 3.2.5 on 2022-02-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_transactiondetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
