# Generated by Django 3.2.5 on 2022-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_transactiondetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='date',
            field=models.TextField(default='none', max_length=30),
        ),
    ]
